services:
  frontend:
    build:
      context: ..
      dockerfile: docker-local/Dockerfile

    container_name: bns

    ports:
      - "3000:3000"

    volumes:
      - ..:/app

    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - CHOKIDAR_USEPOLLING=true

    command: sh -c "bun install && bun dev"
