services:
  frontend:
    build:
      context: ..
      dockerfile: docker-local/Dockerfile

    container_name: next-app

    ports:
      - "3000:3000"

    volumes:
      - ..:/app

    command: sh -c "bun install && bun dev"
